### ISSUE TITLE
fft1d has issues for higher lengths > 32

### ISSUE THREAD

**Issue by cdoshi** [wellflat/javascript-labs#1]
HI,
The FFT seems to work for data of length 32  (the example on the github works). The results are the same when compared by computing FFT in matlab. For data of higher lengths (~16384) however the FFT seems to give weird results (values are very high as compared to Matlab) gives results of the order of 10^-13 while this toolbox gives values in range of 10-100s. Any ideas? 
Thanks,
Chiran

**Comment by andcastillo** [comment]
Now you have to push your fix and close the issue. The bug still existing.

**Comment by jee7** [comment]
But it is not a fix, it's a hack. Like I mentioned, there should be a proper fix, that will take the _n into account etc.

**Comment by wellflat** [comment]
fix the bug, close this issue.
